#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Optical Flow)
#
# @type Quadrotor Wide
#

sh /etc/init.d-posix/10016_iris

if [ $AUTOCNF = yes ]
then
	# EKF2
	param set EKF2_AID_MASK 3
    param set EKF2_OF_DELAY 10.0
    param set EKF2_OF_QMIN 10
    param set EKF2_OF_N_MIN 0.05
    param set EKF2_OF_N_MAX 0.2

	# LPE
	param set LPE_FUSION 243
	param set LPE_FAKE_ORIGIN 1
    param set LPE_FLW_QMIN 10
    param set LPE_FLW_SCALE 1.0
    param set LPE_FLW_R 0.2
    param set LPE_FLW_RR 0.0

	param set MPC_ALT_MODE 2
    param set SENS_FLOW_ROT 0
    param set SENS_FLOW_MAXHGT 4.0
    param set SENS_FLOW_MINHGT 0.01
    param set SENS_FLOW_MAXR 5.0
fi
