#!/bin/sh
#
# @name COEX Clover 4 (simulated) with Optical Flow
#
# @type Quadrotor X
#

sh /etc/init.d-posix/1500_clover4

if [ $AUTOCNF = yes ]
then
	# EKF2
	param set EKF2_AID_MASK 1
    param set EKF2_OF_DELAY 0
    param set EKF2_OF_QMIN 10
    param set EKF2_OF_N_MIN 0.05
    param set EKF2_OF_N_MAX 0.2

	# LPE
	param set LPE_FUSION 20
    param set ATT_W_EXT_HDG 0.5
    param set ATT_EXT_HDG_M 1
    param set LPE_VIS_XY 0.1
    param set LPE_VIS_Z 0.1
    param set LPE_VIS_DELAY 0
	param set LPE_FAKE_ORIGIN 1
    param set LPE_FLW_QMIN 10
    param set LPE_FLW_SCALE 1.0
    param set LPE_FLW_R 0.2
    param set LPE_FLW_RR 0.0

	param set MPC_ALT_MODE 2
    param set SENS_FLOW_ROT 0
    param set SENS_FLOW_MAXHGT 4.0
    param set SENS_FLOW_MINHGT 0.01
    param set SENS_FLOW_MAXR 5.0
fi
